name: build-isosim-workflow
on:
  push:   
    branches: 
      - master
  schedule:
  - cron: '0/15 * * * *'

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: run
      uses: cedrickring/golang-action@1.5.1
